import net.turfclub.*
/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        
                
        auth(controller: "*", action: "*") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (controllerName == "event" & actionName == "todaysEvent") {
                    return true
                }

                // Access control by convention.
                accessControl()
            }
        }
    }
}
